name: Question or Support
description: Ask a question or request help with using the ollama-n8n-stack
title: "[Question]: "
labels: ["question", "support"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Need Help? 🤝
        
        Before creating a question issue, please check:
        - 📖 [Documentation](https://github.com/your-org/ollama-n8n-stack/blob/main/README.md)
        - 💬 [Existing discussions](https://github.com/your-org/ollama-n8n-stack/discussions)
        - 🐛 [Known issues](https://github.com/your-org/ollama-n8n-stack/issues)

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is your question about?
      options:
        - General/Setup
        - MCP Server
        - MCP Client
        - MCP HTTP Bridge
        - Ollama Integration
        - N8N Integration
        - Neo4j Integration
        - Home Assistant Integration
        - Docker Setup
        - GitHub Actions/CI/CD
        - Documentation
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Installation/Setup
        - Configuration
        - Usage/How-to
        - Integration
        - Troubleshooting
        - Best practices
        - Architecture/Design
        - Performance
        - Security
        - Contributing
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: |
        Please be as specific as possible:
        - What are you trying to achieve?
        - What have you tried so far?
        - What specific aspect needs clarification?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide additional context about your setup or use case
      placeholder: |
        Helpful context might include:
        - Your environment (OS, Docker version, etc.)
        - Your specific use case or goal
        - Relevant configuration
        - What you've already tried

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: If your question relates to setup or troubleshooting, please provide environment details
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13, Windows 11]
        - Docker version: [e.g., 24.0.0]
        - Docker Compose version: [e.g., 2.20.0]
        - Browser: [e.g., Chrome 120, Firefox 121]
        - Any other relevant versions

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this question?
      options:
        - Low - General inquiry
        - Medium - Blocking current work
        - High - Production issue
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have provided sufficient context for my question
          required: true
        - label: This is not a bug report (I would use the bug report template for that)
          required: true